syntax = "proto3";
option csharp_namespace = "gRPCDocuments.Protos";
package Document;
service DocumentService {
  rpc GetAll (Empty) returns (DocumentList);
  rpc GetAllByPatientId (PatientId) returns (DocumentList);
  rpc GetOneByDocumentId (DocumentId) returns (GrpcDocument);
  rpc Post (GrpcPostDocument) returns (Empty);
  rpc Put (GrpcPutDocument) returns (Empty);
  rpc DeleteAll (Empty) returns (Empty);
  rpc DeleteAllByPatientId (PatientId) returns (Empty);
  rpc DeleteOneByDocumentId (DocumentId) returns (Empty);
}

message Empty{}

message PatientId {
  string id = 1;
}

message DocumentList{
    repeated GrpcDocument list = 1; 
}

message DocumentId {
  string id = 1;
}

message GrpcDocument {
  string documentId = 1;
  string patientId = 2;
  string url = 3;
}

message GrpcPostDocument {
  string patientId = 1;
  string url = 2;
}

message GrpcPutDocument {
  string documentId = 1;
  string patientId = 2;
  string url = 3;
}
